# Generated by Django 3.2.7 on 2021-09-10 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugboapi', '0002_auto_20210910_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameModel(
            old_name='Priority',
            new_name='BugPriority',
        ),
        migrations.AddField(
            model_name='bug',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bugboapi.bugtype'),
            preserve_default=False,
        ),
    ]
