# Generated by Django 3.2.7 on 2021-09-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugboapi', '0003_auto_20210910_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='entry_date',
            field=models.DateField(default="2021-09-23"),
            preserve_default=False,
        ),
    ]
