# Generated by Django 3.2.7 on 2021-09-13 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugboapi', '0004_bug_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='owner',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bugboapi.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='tags',
            field=models.ManyToManyField(through='bugboapi.BugTag', to='bugboapi.Tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='assignees',
            field=models.ManyToManyField(through='bugboapi.ProjectUser', to='bugboapi.Employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='bugs',
            field=models.ManyToManyField(through='bugboapi.BugProject', to='bugboapi.Bug'),
        ),
        migrations.DeleteModel(
            name='BugOwner',
        ),
    ]
