# Generated by Django 3.2.7 on 2021-09-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugboapi', '0006_alter_bug_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='bugboapi.employee'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='bugboapi.employee'),
        ),
    ]
