# Generated by Django 3.2.7 on 2021-09-20 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugboapi', '0007_auto_20210913_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='owner',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='bugboapi.employee'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='bugboapi.bugstatus'),
        ),
    ]
